version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi
    networks:
      - app-network

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - fastapi-db:/app
    networks:
      - app-network

volumes:
  fastapi-db:

networks:
  app-network:
    driver: bridge
